{
 "title": "Missing Value in the Dataset ",
 "time": { "from": "2022-02-01T18:32:08.000Z", "to": "2022-02-27T17:09:23.000Z" },
 "panels": [
  {
   "title": "Predictoin Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT share_missing_value, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drift Colunms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}